version: '3'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # RabbitMQ management UI
      - "5672:5672"   # RabbitMQ main port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tmsnet

  training-services:
    build:
      context: .
      dockerfile: training_service/Dockerfile

    networks:
      - tmsnet

networks:
  tmsnet:
    driver: bridge